### ISSUE TITLE
Unhandled Exception - Win10

### ISSUE THREAD

**Issue by Geowil** [MarcoPNS/Spotify-Stream-Widget#69]
Getting this occasionally while the widget is running after several hours.  Will happen multiple times even after closing the widget, reopening, and reconnecting to Spotify.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Spotify_Stream_Widget.Viewer.VB$StateMachine_42__spotify_OnAccessTokenExpired.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

**Comment by MarcoPNS** [comment]
Hi! Thank your the info. Can you upload your log file? You can find it in in the application folder under `/Logs/`

**Comment by Geowil** [comment]
[2022-09-15.log](https://github.com/MarcoPNS/Spotify-Stream-Widget/files/9595373/2022-09-15.log)
Here you go.

**Comment by MarcoPNS** [comment]
@Geowil Thank you! Could you update to 1.5 and see if it still happens?

**Comment by MarcoPNS** [comment]
Could you send me the new log file?

**Comment by Geowil** [comment]
[2022-09-19.log](https://github.com/MarcoPNS/Spotify-Stream-Widget/files/9598105/2022-09-19.log)

**Comment by MarcoPNS** [comment]
Could you try out this beta release? https://github.com/MarcoPNS/Spotify-Stream-Widget/raw/main/Release/Spot_Widget_1_5_0_1.zip

**Comment by Geowil** [comment]
The errors have stopped, however the issue still happens occasionally.  When it does, the widget stops updating.  Here is yesterday's log.
[2022-09-20.log](https://github.com/MarcoPNS/Spotify-Stream-Widget/files/9618014/2022-09-20.log)

**Comment by MarcoPNS** [comment]
This is actually very interesting! The timer fails and there is no refresh. The app doesn't even try. 

Thank you! I'll try to prepare a second beta. I think it should be fixed then.

**Comment by MarcoPNS** [comment]
The new beta should work! https://github.com/MarcoPNS/Spotify-Stream-Widget/raw/main/Release/Spot_Widget_1_5_0_2.zip

**Comment by Geowil** [comment]
Still getting auth issues.  If the auth is lost and after attempting to reconnect the widget to Spotify, the widget crashes if auth access is lost again.
